# Generated by Django 4.0.4 on 2022-04-21 02:46

from django.db import migrations, models
import uploadapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=uploadapp.models.upload_path)),
            ],
        ),
    ]
