# Generated by Django 4.0.4 on 2022-04-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='caption',
        ),
    ]
